apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: dns-operator-catalog
spec:
  sourceType: grpc
  image: quay.io/kuadrant/dns-operator-catalog:v0.16.0
  displayName: DNS Operators
  publisher: grpc
