apiVersion: kuadrant.io/v1alpha1
kind: DNSRecord
metadata:
  name: dnsrecord-loadbalanced-coredns-cluster3
spec:
  rootHost: loadbalanced.k.example.com
  endpoints:
    - dnsName: loadbalanced.k.example.com
      recordTTL: 300
      recordType: CNAME
      targets:
        - klb.loadbalanced.k.example.com
    - dnsName: klb.loadbalanced.k.example.com
      providerSpecific:
        - name: geo-code
          value: US
      recordTTL: 300
      recordType: CNAME
      setIdentifier: US
      targets:
        - us.klb.loadbalanced.k.example.com
    - dnsName: us.klb.loadbalanced.k.example.com
      providerSpecific:
        - name: weight
          value: "100"
      recordTTL: 60
      recordType: CNAME
      setIdentifier: cluster3-gw1-ns1.klb.loadbalanced.k.example.com
      targets:
        - cluster3-gw1-ns1.klb.loadbalanced.k.example.com
    - dnsName: cluster3-gw1-ns1.klb.loadbalanced.k.example.com
      recordTTL: 60
      recordType: A
      targets:
        - 172.18.200.3
  delegate: true
