apiVersion: kuadrant.io/v1alpha1
kind: DNSRecord
metadata:
  name: dnsrecord-simple-coredns-cluster2
spec:
  rootHost: simple.k.example.com
  endpoints:
  - dnsName: simple.k.example.com
    recordTTL: 60
    recordType: A
    targets:
    - 172.18.200.2
  delegate: true
